### PR TITLE
Add ability to filter the environment variables

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Review by danduk82 — CHANGES_REQUESTED** [review]
actually, I was wondering if instead of passing the whole environment, and filtering our some stuff, if we shouldn't instead whitelist the `passEnv` environment variables that are really useful and write them directly to a config file.

**Comment by sbrunner** [comment]
Personally, I prefer not to introduce to read a config file in bash...

**Comment by danduk82** [comment]
mmh, why read it? just write the FCGI config file in the image and that's it.

**Comment by sbrunner** [comment]
No, it's not so simple, we also find a way to build this file, and to give it to the container, for me, it's to complicate to integrate...

**Review by danduk82 — APPROVED** [review]
lgtm

**Pull request merged**
