### PR TITLE
Enable 3D

### PR DESCRIPTION
**Pull request by yjacolin**

### CODE REVIEW

**Review by ismailsunni — APPROVED** [review]
LGTM

**Comment by sbrunner** [comment]
I'm not sure that's a good idea to enable this on an image made for the server, I think that we should create 2 different images (e.-g. Differentiate by tag '3.16-client'), and with multistage build, we should be able to take benefit of the cache.
Someone will work on this direction (I also can do it).

**Review by sbrunner — CHANGES_REQUESTED** [review]
I'm not sure that's a good idea to enable this on an image made for the server, I think that we should create 2 different images (e.-g. Differentiate by tag '3.16-client'), and with multistage build, we should be able to take benefit of the cache.
Someone will work on this direction (I also can do it).

**Comment by yjacolin** [comment]
I agree to split image in 2 images server and client.

**Pull request closed without merging**
